import Head from "next/head";
import {
  ItemList,
  ListContainer,
  Categories,
  CitySelector,
} from "../../styles/List";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { listStoresController } from "../../controllers/Restaurants.controller";
import { IStores } from "../../interfaces/IStores";
import Loader from "../../components/Loader";
import { calcRating } from "../../utils/calcRating";

export default function Home() {
  const router = useRouter();
  const [restaurants, setRestaurants] = useState<IStores[]>([]);
  const [filterBy, setFilterBy] = useState("");
  const [loading, setLoading] = useState(true);
  const [citySelected, setCitySelected] = useState("");

  useEffect(() => {
    loadData();
  }, [citySelected]);

  const loadData = async () => {
    const result = await listStoresController(citySelected);
    setRestaurants(result);
    setLoading(false);
  };

  const handleClick = (id: string) => {
    router.push(`/app/restaurant/${id}`);
  };

  const handleCategory = (title: string) => {
    router.push(`/app/category/${title}`);
  };

  const categories = [
    {
      color: "orange",
      title: "Lanches",
      image: "hamburguer.svg",
      api: "lanche",
    },
    {
      color: "blue",
      title: "Pizzarias",
      image: "pizzaria.svg",
      api: "pizza",
    },
    {
      color: "purple",
      title: "Barzinhos",
      image: "drink.png",
      api: "barzinho",
    },
    {
      color: "red",
      title: "Restaurante",
      image: "meat.svg",
      api: "restaurante",
    },
    {
      color: "pink",
      title: "Doces",
      image: "candy.svg",
      api: "doces",
    },
    {
      color: "coral",
      title: "Japonês",
      image: "sushi.svg",
      api: "japones",
    },
    {
      color: "brown",
      title: "Cafeteria",
      image: "coffee.svg",
      api: "cafeteria",
    },
    {
      color: "green",
      title: "Massas",
      image: "pasta.svg",
      api: "massas",
    },
  ];

  return (
    <>
      <Head>
        <title>Urunga - List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListContainer>
        <Image
          src={"/logo.svg"}
          alt={"RatingStar"}
          height={88}
          width={88}
          className="logo-icon"
        />
        <CitySelector>
          <select
            name="cars"
            id="cars"
            value={citySelected}
            onChange={(e) => setCitySelected(e.target.value)}
          >
            <option value="" disabled>
              Escolha sua Cidade
            </option>
            <option value="jundiai">Jundiaí</option>
            <option value="varzeapta">Várzea Paulista</option>
            <option value="campolimpopta">Campo Limpo Paulista</option>
          </select>
        </CitySelector>

        <div className="search-bar">
          <Image
            src={"/icons/question-mark.svg"}
            alt={"RatingStar"}
            height={15}
            width={15}
          />

          <input
            type="text"
            placeholder="Pesquisar restaurante"
            value={filterBy}
            onChange={(e) => setFilterBy(e.target.value)}
          />
        </div>
        <Categories>
          <h2>Categorias</h2>
          <div className="category-group">
            {categories.map((item, index) => {
              return (
                <div
                  key={index}
                  className="category-item"
                  onClick={() => handleCategory(item.api)}
                >
                  <div className={item.color}>
                    <Image
                      src={`/icons/${item.image}`}
                      alt={item.title}
                      height={40}
                      width={40}
                    />
                  </div>
                  <p>{item.title}</p>
                </div>
              );
            })}
          </div>
        </Categories>

        <ItemList>
          <h2>Restaurantes</h2>
          {loading ? (
            <div className="loaderContainer">
              <Loader />
            </div>
          ) : (
            <>
              <ul>
                {restaurants
                  .filter((item) =>
                    item.name.toLowerCase().includes(filterBy.toLowerCase())
                  )
                  .map((item) => {
                    return (
                      <li key={item._id} onClick={() => handleClick(item._id)}>
                        <div className="image-holder">
                          <Image
                            src={item.logo}
                            alt={"RatingStar"}
                            height={88}
                            width={88}
                          />
                        </div>
                        <div className="info-box">
                          <p>{item.name}</p>
                          <div className="info-icons">
                            {item && item.veggie && (
                              <div className="tooltip-container">
                                <Image
                                  src={"/images/vegan.png"}
                                  alt={"pet"}
                                  height={18}
                                  width={18}
                                  style={{ marginRight: 10 }}
                                />
                                <span className="tooltiptext">Veggie</span>
                              </div>
                            )}
                            {item && item.petFriendly && (
                              <div className="tooltip-container">
                                <Image
                                  src={"/images/pet.png"}
                                  alt={"pet"}
                                  height={18}
                                  width={18}
                                  style={{ marginRight: 10 }}
                                />
                                <span className="tooltiptext">
                                  Pet Friendly
                                </span>
                              </div>
                            )}
                            {item && item.kids && (
                              <div className="tooltip-container">
                                <Image
                                  src={"/images/kids.png"}
                                  alt={"pet"}
                                  height={18}
                                  width={18}
                                  style={{ marginRight: 10 }}
                                />
                                <span className="tooltiptext">Espaço kids</span>
                              </div>
                            )}
                            {item && item.accessibility && (
                              <div className="tooltip-container">
                                <Image
                                  src={"/images/chair.png"}
                                  alt={"pet"}
                                  height={18}
                                  width={18}
                                  style={{ marginRight: 10 }}
                                />
                                <span className="tooltiptext">
                                  Acessibilidade
                                </span>
                              </div>
                            )}
                            {item && item.mealTicket && (
                              <div className="tooltip-container">
                                <Image
                                  src={"/images/mealTicket.jpeg"}
                                  alt={"mealTicket"}
                                  height={18}
                                  width={18}
                                  style={{ marginRight: 10 }}
                                />
                                <span className="tooltiptext">
                                  Vale Refeição
                                </span>
                              </div>
                            )}
                            {item && item.lactoseFree && (
                              <div className="tooltip-container">
                                <Image
                                  src={"/images/lactoseFree.jpeg"}
                                  alt={"lactoseFree"}
                                  height={18}
                                  width={18}
                                  style={{ marginRight: 10 }}
                                />
                                <span className="tooltiptext">
                                  Lactose Free
                                </span>
                              </div>
                            )}
                            {item && item.glutenFree && (
                              <div className="tooltip-container">
                                <Image
                                  src={"/images/glutenFree.jpeg"}
                                  alt={"glutenFree"}
                                  height={18}
                                  width={18}
                                  style={{ marginRight: 10 }}
                                />
                                <span className="tooltiptext">Gluten Free</span>
                              </div>
                            )}
                          </div>
                          <span>{item.description}</span>
                          <div className="ratings">
                            <Image
                              src={"/icons/start.svg"}
                              alt={"RatingStar"}
                              height={10}
                              width={10}
                            />
                            <label>{calcRating(item)}</label>
                            <small>({item.rating.length} avaliações)</small>
                          </div>
                        </div>
                      </li>
                    );
                  })}
              </ul>
              {restaurants.filter((item) =>
                item.name.toLowerCase().includes(filterBy.toLowerCase())
              ).length === 0 && <p>Nenhum Restaurante encontrado</p>}
            </>
          )}
        </ItemList>
      </ListContainer>
    </>
  );
}
